### ISSUE TITLE
Proposal: add examples to pharamr.org `Examples` tab or delete altogether

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/pharmaR#11]
On the Examples page, found via `Validation` tab, then clicking `Examples`:

![image](https://github.com/pharmaR/pharmaR/assets/17878953/a82fcc96-6ab9-4f52-9fde-a2d0229d7749)

The page skeleton was set up, but it contains no content. If we don't want to get in the business of furnishing examples, I think it'd make sense to just remove this page altogether.

![image](https://github.com/pharmaR/pharmaR/assets/17878953/f418d7a6-e5a6-4714-9508-e28f6ee7253c)

**Comment by jmanitz** [comment]
What about featuring the case studies there? We spoke yesterday with the R consortium marketing team who would help us to work over those

**Comment by AARON-CLARK** [comment]
> What about featuring the case studies there?

I think that makes a lot of sense. Although, the case studies already have a prominent feature below. Would there be different content on each page?

![image](https://github.com/pharmaR/pharmaR/assets/17878953/93a3541a-6b91-4182-b4cd-eafb20e051c3)

**Comment by jmanitz** [comment]
We were discussing with the R consortium to revisit case study by cutting the presentations into pieces and combine it with a follow-up interview a year later.

**Comment by dgkf** [comment]
I'd be in favor of offloading the examples to their respective projects. In this case, I think linking out to `{riskassessment}` or `{riskmetric}`'s docs or vignettes would be sufficient and would let the teams that own these products keep them up-to-date alongside their project (and in a more standard format).

**Comment by AARON-CLARK** [comment]
I second @dgkf's motion.

**Comment by jmanitz** [comment]
Agree that would be best to link to vignettes as suggested above. Then, the example tab becomes a place where we highlight different implementations of the framework compiled by the R consortium marketing team based on the case studies?
