### ISSUE TITLE
Proposal: feature `{riskassessment}` somewhere on pharmar.org

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/pharmaR#12]
The only place I see the `riskassessment` app mentioned is on the `Get Involved` tab under "Contribute". I would argue two options:

* we could add a `riskassessment` blurb to the existing "Risk Assessment" page, which is currently filled with `riskmetric` content.

* we could rename the "Risk Assessment" dropdown value to `riskmetric` and the `riskassessment` app could have it's own page called "Risk Assessment App"

I'd be happy to draft up the PR. Thoughts?

**Comment by jmanitz** [comment]
Good idea, either works, but I think the first suggestion will be easier.
