### ISSUE TITLE
Recruitment for "Business Strategy" workstream

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/pharmaR#16]
@dgkf, I sent the following email to one of the higher-ups within my org and they definitely want to contribute someone to participate. I also have recruited a second candidate outside my org who could fit the role well. However, I'm wondering "what's next" for these people? Do you want me to keep them in a holding pattern until a kick-off meeting is scheduled? Do you want to have a 1:1 with them to see if they'd be a good fit? Or perhaps some other option? Thanks!

# Recruitment Email:
If anyone else wants to adapt the following email for their recruitment efforts, please feel free to use what you want from the following email template:

### Subject:
R Validation Business Strategy

### Body:
Hi xxxxxxx,

I serve as an executive committee for the [R Validation Hub](https://www.pharmar.org/), a consortia of ~50 pharma orgs dedicated to designing/building a framework to validate R and R packages (with an eye to all open-source languages in the future, not just R). Our company has been heavily involved in several of their work streams since the effort started ~ 5-ish years ago, and we’ve made great progress. We’ve published several white papers and created open-source software to help pharma orgs adopt a risk-based approach to validation.

Recently, we performed an internal audit on ourselves and concluded we have loads of technical minds working hard on solutions but are lacking an assembly of business minded professionals to help guide our validation efforts and advocate for business needs/desires during the validation journey. As a result, we’re kick starting a new group called the “Business Strategy” work stream and are seeking key stakeholders to get involved. New members will be filled from a subset of pharma orgs first (those orgs who have exec roles with the R Validation Hub) and if needed, we’ll open our recruitment efforts to the broader ~50 or so pharma orgs represented in the R Validation Hub.

Wondering if you may have someone you’d like to nominate from your team to fill such a role? The benefit would mean our company will play a major role in shaping how the industry addresses validation from a business perspective, forming a consensus that will be adopted by many pharma orgs. Happy to provide additional details as needed!

Thanks,
Aaron

**Comment by dgkf** [comment]
Awesome, thanks Aaron! Let's discuss tomorrow. 

My impression is that we'll probably want to pull this group together ~4 times a year to do some quarterly planning type activities. My hope is that the benefit of being involved goes both ways - I think this will help us to be more intentional about our longer-term goals and hopefully means that leaders across the industry are more aware of our goals before they reach completion.

**Comment by AARON-CLARK** [comment]
Seems like we can close this one since we'll be relying on the R Consortium's "Pharma Oversight Committee" going forward, as discussed in #21
