### ISSUE TITLE
Exec Meeting (2023/08/08)

### ISSUE THREAD

**Issue by dgkf** [pharmaR/pharmaR#22]
### Previous Action Items:

- [x] Discussed moving blog posts to R/Consortium webpage or cross posing blogs posts.
   > Decision: leave as judgement call to in-formation Communications WS
- [ ] Send off previous recording for upload to R Consortium YouTube channel (Juliane went ahead and started coordinating with SCC)

### Agenda

- Welcoming Coline, joining for first time as representative of Repositories WS
- Welcome our newest Communications WS team members (Jaxon & Anuja)
- R/Pharma submissions (deadline Aug 11th) - Workshop proposal and talk abstract submission coordination (@AARON-CLARK)
- Round table discussions

**Comment by AARON-CLARK** [comment]
> * R/Pharma submissions (deadline Aug 11th) - Workshop proposal and talk abstract submission coordination (@AARON-CLARK)

Sent email checking in with Phil B since he coordinates the workships. Email CC'd Eric & Doug.

**Comment by dgkf** [comment]
@AARON-CLARK Regarding the R/Pharma sessions: Coline put in an abstract for a talk about the repositories wg and was instead offered a workshop slot. This was a bit surprising, since our work in the repositories wg is more investigative/pilot phase - which feels like it would map more nicely into a talk than a workshop.

I'll loop Coline into the dialog with Phil. I could see a path where the planning committee thought the Repositories WG abstract was more broadly covering all R Validation Hub efforts and maybe then it makes sense to merge the workshop efforts between the repositories wg and the riskassesssment work.

**Comment by dgkf** [comment]
## R/Pharma Planning Updates

- @Crosita was offered a workshop slot, although it does not necessarily need to be R Validation Hub specific. Coline to decide how she feels the slot will best be used based on other accepted talks/workshops
- @jmanitz planning to give 10 minute lightning talk overview of ongoing activities
- @AARON-CLARK in discussions with organizing committee to potentially get a R Validation Hub specific workshop slot, which may either allow us to split technical tooling (riskmetric/riskassessment/riskscore) and infrastructure/process (repositories wg), or free up Coline's slot to cover other ground.

## Round-table Updates

### R Consortium Updates:

* Joe will remain involved with R Consortium and the R Validation Hub :tada: 
* Submissions working group: 
  * Pilot 4, packing of a clinical trial exploring containers (podman) and wasm
  * Shipping R packages as .zip/.tar.gz archive, currently sourced from github, but could be RValHub repo or binaries
  * Possible to explore using `pkglite` (and upcoming successor)
* R Consortium Repositories WG
  * Repositories standards, ie - what does a trusted package look like?
  * Considering validated "portfolios" of packages, which may be useful for a clinical submission
  - [ ] @Crosita @dgkf: In coming months, it would be the right time to get someone more directly involved from the R Val Hub Repositories WG. Joe advises involving someone quite technical as the discussions go very deep.
* R Consortium "Marketing" now Community Development committee

### Communications Updates:

- [x] @dgkf: to publish blog post (https://github.com/pharmaR/pharmaR.github.io/pull/95)
- [ ] @dgkf: to reach out to SCC with notes following Aug 9th/16th seminar series, passing on title, abstract, recordings and recap bullet points
- [x] @dgkf: to put our new communications workstream members in contact with workstream leads to do a tour of workstreams and build network among the various initiatives. 
- [x] @jmanitz to organize intro meeting with new members and @joseph-rickert to make sure we're developing the right communication channels through the R Consortium

### Repositories Workstream

- Currently wrapping up individual workflow pilots, to be wrapped into holistic project plan 
- Well-received presentation at UseR!, leading to lots of new interest

### `riskmetric`, `riskscore`

- Ongoing development going smoothly
- Priority currently is seminar tomorrow, and follow-up in a week
