### ISSUE TITLE
R Validation Hub chat platform?

### ISSUE THREAD

**Issue by dgkf** [pharmaR/pharmaR#3]
There's recently be more of an interest in reigniting a chat platform for the R Validation Hub. 

We raised this when forming the repos working group, and has recently been raised with the pharmaverse acceptance of `riskmetric` and `riskassessment`. With the launch of a comms workstream, and the recognition that we can probably do more community engagement and long-term planning, having a forum for more immediate communication might help tackle some of these gaps.

So I'm opening this primarily as a pulse check for our team. Is this something we think would be valuable? 

Capture a few different proposals:

- If the primary users are going to be the tools workstreams (`riskmetric` and `riskassessment`) and they feel they can reach a wider audience on the pharmaverse slack, then maybe this problem is best solved over there
- If we want a chat channel, we can resuscitate our Slack group
- Or, I think the Linux Foundation might offer chat hosting via [chat.lfx.linuxfoundation.org](http://chat.lfx.linuxfoundation.org/). @joseph-rickert, is this something that we could use? Do you think it's suitable for us?

**Comment by joseph-rickert** [comment]
Hi Doug,
I will follow up and see about the LF chat channel.

BEst,
joe

Joseph B. Rickert
R Consortium Director
Posit R Community Ambassador
408.489.0566

**Comment by dgkf** [comment]
Tagging @AARON-CLARK and @emilliman5 - Have you moved to the pharmaverse slack? If not, were you still interested in possibly revitalizing the R Validation Hub slack channel?

We're also exploring the use of the Linux Foundation's matrix chat server, but whether that's a viable solution is still TBD.

**Comment by AARON-CLARK** [comment]
I didn't make any moves yet because I was still pondering the subject.

- I think joining the pharmaverse's chat still poses a lot of benefits, popularity being #1.
- We are currently using the R Val Hub slack via a private channel for dev team communication, and occasionally the public `riskassessment` channel. I think there are like 60-ish people subscribed that that channel.
- I don't really know anything about LF matrix chat, which maybe is a good indicator that we shouldn't use it? 😅 Do other people know about and use it? Maybe I'm not in the loop.

**Comment by emilliman5** [comment]
We have not moved. Nor do I really see a need, at the moment. Our team interacts mainly through GH and our bi-weekly sprints. Our current slack channel is quite dead. Now maybe if we move to pharmaverse there would be more activity, but I'm not sure how I feel about that or if it would be helpful...

**Comment by dgkf** [comment]
Thanks both! I'm also unsure of the need right now and if the right path is to stick with comms on GitHub that's fine by me.

**Comment by dgkf** [comment]
Just relaying a communication from the Linux Foundation's Director of Program Management community organizer reached out and endorsed slack. They said we are free to continue using our Slack workspace and that they can help to kick off groups and coordinate invites if we need it.

Based on this discussion, let's stick with GH primarily and we can reevaluate if we get another swell of requests for alternative comms.
