### ISSUE TITLE
ProCogia's (free) Posit Connect License Restricted

### ISSUE THREAD

**Issue by aclark02-arcus** [pharmaR/pharmaR#37]
From #36:

> Joe expressed concern about the risk assessment app from Procogia report: "license revoked" message. Momentum lost. Where to revive it? R Consortium server? Posit Connect Cloud as home? @AARON-CLARK

Hi @joseph-rickert!

Regarding the license snafu, this is the email I got from Brian Carter, who I got the chance to meet in person last week at Posit Conf:

> I know you are probably frustrated with the hosting of your application, and I wanted to update you on a couple things.  While we were dealing with the license updates from Posit, they saw that we were hosting your application and pointed out that our license did not allow us to do this, so we can no longer use our Connect account to host it.  They have also removed the ability for us to host interactive applications publicly and they really don’t want any application on Connect to use a login screen like you have configured.  Honestly, it is all kind of a mess right now, but the short story is that even if we ignored Posit, we could not get this back up for you on Connect because that capability is no longer available.
> 
> I have asked Momin to migrate everything to an open source Shinyserver and use the same URL so we can get back up and running, but we have run into some problems with the application.  The error we are getting is… [redacted by Aaron].

So, everything was migrated to open-source `shinyserver` so we're fully operational and [shared the link in our slides for Posit Conf](https://pharmar.github.io/events-positconf2024/#/new-collaborative-deployment). I think Posit just didn't expect folks to be using ProCogia's free license for a publicly hosted application. @dgkf had a hypothesis that perhaps Posit was trying to avoid the possibility of user-level data storage that would require them to be accountable to GDPR things. In any event, I'll follow up with Brian for more details to make sure we're not stepping on anyone's toes.

**Comment by joseph-rickert** [comment]
@aclark02-arcus 
Hi Aaron,
Thank you for the update. It seems like this turned out to be a more complicated business problem than anyone expected.
It appears that the  app is up and running on the shinyserver. which I suppose is fine for now.
However in the long run, I think we will want to find a way to put the app up on an R Validation Hub/ R Consortium property.

**Comment by aclark02-arcus** [comment]
> find a way to put the app up on an R Validation Hub/ R Consortium property

@joseph-rickert, `shinyserver` is like the open-source version of Posit Connect... kind of. But it is hosted on a server the ProCogia is managing... so I think that's still considered an R Validation Hub / R Consortium property by the transitive property.

**Comment by aclark02-arcus** [comment]
We received a follow up email from Brian clarifying the situation, so I think we can mark this issue as "resolved".

> Hi Aaron, 
> 
> Yeah, it is actually a touchy subject with Posit.  First of all, we don’t have a normal license.  Since we are partners with Posit, they give us the software for free.  But technically we are only allowed to use it to provide demos to customers or as a sandbox to debug or develop custom solutions to clients.  We aren’t actually allowed to use it as intended.  Lesson learned.
> 
> But even if we did have a grown up license, their licensing does not actually allow you to use your app as you want to.  They don’t really want people sharing Connect applications to the wider internet, they only want named users (i.e. members of an organization that are paying for the license) to access a Connect app.  You can pay them extra money to enable to option to share applications to the wider internet, but that’s just more money.  Moreover, they absolutely forbid any application on Connect to have some kind of additional login authentication, including the minimal one on your landing page.  So if Arcus was to purchase the biggest and greatest Connect server and you chose to migrate it there, you still would not be able to share it like you are with external users.
> 
> When I originally proposed moving your application to our Connect account, I was unaware of any of these things.  First, I thought we had a normal license and I could do whatever I wanted within my budget.  But when we renewed the license, that’s when all those nice options were disabled.  We complained to Posit and told them that we were hosting risk assessment and they educated me.

I heard Posit is moving to a new license model that doesn’t favor “anonymous” users, so this makes sense. And yes, internally, we don’t use the {shinymanager} auth screen – it is a completely optional configuration leveraged just for our Demo app and for users. Internally, we leverage AD groups to build roles around actual authenticated Connect users, like Posit has designed.
