### ISSUE TITLE
Meeting minutes 09May 2023

### ISSUE THREAD

**Issue by DrLynTaylor** [pharmaR/pharmaR#7]
## Attendees:

Doug Kelkoff (Chair/Repository lead, Roche) 
Andy Nicholls (GSK) 
Lyn Taylor (Parexel/CAMIS lead) 
Eric Milliman (Biogen/riskmetric lead)
Aaron Clark (Biogen/ R Shiny App lead)
Juliane Manitz (Merck Serono/ Comms lead) 
Joe Rickert (R Consortium/R Studio)
Preetham Palukuru (Merck)

## Apologies:
Keaven Anderson (Merck)
Paulo Bargo (Janssen R&D)

## Agenda

- Recap communications workstream kickoff
  - Kickoff of repo for minutes, administration and strategic discussion ([pharmaR](https://github.com/pharmaR/pharmaR))
  - Meeting notes to move to issues? ([pharmaR #6](https://github.com/pharmaR/pharmaR/issues/6))
  - Small follow-up about chat platform: Linux Foundation is using Slack
  - What would an ideal size of this team look like? Do we need to do any recruiting?
- Discussion of strategic workstream. Discussion points:
  - Who is involved? (is it exactly this group?)
  - What are the goals/deliverables? (how are they organized?)
  - What do meetings look like, how frequently do they occur?
  - How does this group relate to other workstreams?
  - What ongoing tasks do we need to carry forward as action items?
- Time allowing, workstream roundtable

## Communications

Plan to change to the R consortium zoom meeting invite.  

- [x] @Joe to ask Amanda at R consortium to send meeting invites going forward.
   - In order to improve communications – moving to github issues for meeting minutes & actions under this pharmaR repo.
- [x] #8
   - Events will be still kept within the Events repo
   - If we want a discussion platform – linux plan was to just use slack. 
   - Future All Hands Event Meeting series discussion here (https://github.com/pharmaR/pharmaR/issues/2#issuecomment-1540495645)
   - For advertising, we can go through R consortium Jesse Casman [jesse@storychangesculture.com](mailto:jesse@storychangesculture.com)    or Agueda Chavez Gama [agueda@storychangesculture.com]
- [x] @AARON-CLARK  to follow up re: Blog post re: winner of best app at ShinyConf 2023
- [ ] @dgkf  or @jmanitz or @DrLynTaylor to ensure the link / blog goes onto the pharmar website & social media.
   - Due to amount of work within the Communications working group re: general admin, organizing events, website, blogs, marketing suggest we get 1-2 more volunteers to join Lyn & Juliane.  
- [ ] Please all check within your workstream if anyone would be interested in joining the Communications workstream. 

## Discussion of strategic workstream

- How do we be more decisive about the direction the group is going in?
- Who is involved? (is it exactly this group?)
   - Few more people, address the business side (senior within organizations) as well as technical.  Bring in people with diverse experience, ensure diversity of opinions, covers other organizations, anyone more senior to join so the needs drives the business – strategic planning? Quality type people may also be useful on the group.  Get representation from other organizations – PHUSE – Data visualization & open source technology (NOTE: Michael Rimler taken up position on PHUSE board),  Transcelerate, Pharmaverse, 
   - [ ] All to see if anyone internally within their companies (with influence or diverse interests) would be interested in joining the strategic workstream.
- What are the goals/deliverables? (how are they organized?)
   - Group charter – Goals in next year – impact we want to achieve.  i.e. for Repo’s working group: mission to make package availability more accessible & package more transparent.  Assessment of packages more publicly available. 
   - Big picture: take on concept of validation – what does it mean and is it useful?  Address the fears of the business.
Elaborate on kinds of risk, what can we address technically.  How do we delegate some activities.  Bring in quality people to get people on board.
- What do meetings look like, how frequently do they occur?
   - Does the exec team live on when we have strategic workstream?  If >1 person on workstream then only 1 attend.
Juliane or Lyn,   Aaron or Eric – on rota to cut down attendance.
- How does this group relate to other workstreams?
   - Monthly strategic workstream meeting.  Rep from workstream & broader direction of team. 
- What ongoing tasks do we need to carry forward as action items?
   - None.
- [ ] next meeting:  workstream round table.  All to look out for new zoom meeting invite

**Comment by dgkf** [comment]
Just a minor follow-up in relation to #6, I was able to convert a checkbox to an issue (mouse over the list item and there will be a circle button that appears on the far right giving you the option to convert to an issue).

I think that taking notes and recording action items as minutes, then converting actions to distinct issues and assigning them out is the best way to go.

**Comment by dgkf** [comment]
Closing this out, we can carry forward any unclosed action items into the action items for the next meeting.
